how can i fix the error with on_content

```rust

 pub async fn stream_request<F>(client: &Client<OpenAIConfig>, messages: &mut Vec<ChatCompletionRequestMessage>, mut on_content: Option<F>) -> Result<String, Box<dyn Error>>
where
    F: FnMut(&str),
{
  let request = CreateChatCompletionRequestArgs::default()
        .model("gpt-3.5-turbo")
        .messages(messages.clone())
        .build()?;

    let mut stream = client.chat().create_stream(request).await?;

    let mut lock = stdout().lock();
    let mut answer = String::new();
    while let Some(result) = stream.next().await {
        match result {
            Ok(response) => {
                response.choices.iter().for_each(|chat_choice| {
                    if let Some(ref content) = chat_choice.delta.content {
                        answer += content.as_str();
                        write!(lock, "{}", content).unwrap();
                        on_content(content);
                    }
                });
            }
            Err(err) => {
                writeln!(lock, "error: {err}").unwrap();
            }
        }
        stdout().flush()?;
    }

    Ok(answer)
}

```